from fpdf import FPDF
import os
import re
from datetime import datetime


def clean(text):
    """Strip emojis and non-Latin-1 characters so fpdf Helvetica doesn't crash."""
    if not isinstance(text, str):
        text = str(text)
    return re.sub(r'[^\x00-\xFF]', '', text).strip()


def generate_report(issue, category, severity, sustainability_score, sdgs, impact, actions):

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Header bar ─────────────────────────────────────────────────────────
    pdf.set_fill_color(34, 139, 34)
    pdf.rect(0, 0, 210, 28, 'F')

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(0, 6)
    pdf.cell(210, 10, "AI Sustainability Navigator", align="C", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_xy(0, 17)
    pdf.cell(210, 8, "Community Sustainability Issue Report", align="C", ln=True)

    pdf.ln(8)

    # ── Date ───────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%B %d, %Y  %H:%M')}", ln=True, align="R")
    pdf.ln(2)

    # ── Section helper ─────────────────────────────────────────────────────
    def section(title):
        pdf.set_fill_color(240, 248, 240)
        pdf.set_text_color(34, 100, 34)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 9, f"  {title}", ln=True, fill=True)
        pdf.set_text_color(30, 30, 30)
        pdf.set_font("Helvetica", "", 11)
        pdf.ln(1)

    # ── Issue ──────────────────────────────────────────────────────────────
    section("Issue Described")
    pdf.multi_cell(0, 7, clean(issue))
    pdf.ln(4)

    # ── Summary table ──────────────────────────────────────────────────────
    section("Analysis Summary")
    col_w = 55
    rows = [
        ("Category", clean(category)),
        ("Severity", clean(severity)),
        ("Sustainability Score", f"{sustainability_score} / 100"),
    ]
    for label, value in rows:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(col_w, 8, label + ":", border=0)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, value, border=0, ln=True)
    pdf.ln(3)

    # Score bar
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, "Score Indicator (0 = critical, 100 = excellent):", ln=True)
    bar_x, bar_y, bar_w, bar_h = 10, pdf.get_y(), 190, 7
    pdf.set_fill_color(220, 220, 220)
    pdf.rect(bar_x, bar_y, bar_w, bar_h, 'F')
    fill_w = int(bar_w * sustainability_score / 100)
    color = (200, 50, 50) if sustainability_score < 50 else (255, 165, 0) if sustainability_score < 75 else (34, 139, 34)
    pdf.set_fill_color(*color)
    pdf.rect(bar_x, bar_y, fill_w, bar_h, 'F')
    pdf.ln(12)

    # ── SDGs ───────────────────────────────────────────────────────────────
    section("SDG Alignment")
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(0, 7, clean(sdgs))
    pdf.ln(4)

    # ── Impact ─────────────────────────────────────────────────────────────
    section("Environmental Impact")
    pdf.multi_cell(0, 7, clean(impact))
    pdf.ln(4)

    # ── Actions ────────────────────────────────────────────────────────────
    section("Recommended Actions")
    pdf.multi_cell(0, 7, clean(actions))
    pdf.ln(6)

    # ── Footer ─────────────────────────────────────────────────────────────
    pdf.set_fill_color(34, 139, 34)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_y(-18)
    pdf.cell(0, 12, "  Generated by AI Sustainability Navigator  |  Powered by IBM Granite + RAG  |  Agentic AI Platform  ", align="C", fill=True)

    # ── Save ───────────────────────────────────────────────────────────────
    os.makedirs("reports", exist_ok=True)
    output_path = os.path.abspath("reports/sustainability_report.pdf")
    pdf.output(output_path)

    return output_path